using Optimization, Dates, Statistics, StatsBase, DataFrames, LinearAlgebra, OptimizationOptimJL, ForwardDiff #,Zygote


"""
    Opp_Log_Monthly_Likelihood_AR(Estimators::AbstractMatrix, x::AbstractVector, date_vec::AbstractVector{Date})

Return the opposite of the log-likelihood of the x series, under the hypothesis that x is generated by an AR(p) 
model with differents set of parameters for each month. For exemple, for the iᵗʰ month, the paramaters are : 
Φ₁,Φ₂...Φₚ=Estimators[i,1:end-1] and σ²=Estimators[i,end].  
This function does not consider the likelihood of the initial conditiion x₁,x₂...xₚ
"""
function Opp_Log_Monthly_Likelihood_AR(Estimators::AbstractMatrix, x::AbstractVector, n2m, p, N)
    EV = [sum(Estimators[n2m[t], i] * x[t-i] for i in 1:p) for t in p+1:N] #Xₜ = EV(t) + ε in our model
    Opplogpdf(t) = (log(2π * abs(Estimators[n2m[t], end])) + ((x[t] - EV[t-p])^2) / Estimators[n2m[t], end]) / 2
    return sum(Opplogpdf.((p+1):N))
end
Opp_Log_Monthly_Likelihood_AR(Estimators::AbstractMatrix, tuple_::Tuple) = Opp_Log_Monthly_Likelihood_AR(Estimators, tuple_[1], tuple_[2], tuple_[3], tuple_[4])

"""
    LL_AR_Estimation_monthly(x_vec::AbstractVector,p::Integer)

Return the parameters of the AR(p) model on x with a set of parameter for each month. 
"""
function LL_AR_Estimation_monthly(x::AbstractVector, date_vec::AbstractVector{Date}, p::Integer, Estimators::AbstractMatrix=stack([[[0.5 for _ in 1:p]; 1e-15] for _ in 1:12], dims=1), algo=LBFGS(); Nb_try=0)
    lb = stack([[[-10 for _ in 1:p]; 1e-20] for _ in 1:12], dims=1)
    ub = stack([[[10 for _ in 1:p]; 1e2] for _ in 1:12], dims=1)
    p == size(Estimators)[2] - 1 ? nothing : error("p (=$(p)) is not equal to the number of Φ initial parameters (=$(length(Estimators)-1))")
    optf = OptimizationFunction(Opp_Log_Monthly_Likelihood_AR, AutoForwardDiff())
    prob = OptimizationProblem(optf, Estimators, (x, month.(date_vec), p, length(x)), lb=lb, ub=ub)
    Results = Optimization.solve(prob, algo, maxiters=10000) #maxiters should be modified if needed
    if !SciMLBase.successful_retcode(Results.retcode)
        @warn "Fail solve"
    end
    # if Nb_try > 0
    for i in 1:Nb_try
        Estimators = rand(12, p + 1) #Reinitialize the parameters
        prob = OptimizationProblem(optf, Estimators, (x, month.(date_vec), p, length(x)), lb=lb, ub=ub)
        localResults = Optimization.solve(prob, algo, maxiters=10000) #maxiters should be modified if needed
        if !SciMLBase.successful_retcode(Results.retcode)
            @warn "Fail solve iteration $(i)"
        end
        if localResults.objective < Results.objective
            Results = localResults
            @info "New best result found with new initialization at iteration $(i)"
        end
    end
    # end
    return Results[:, 1:p], Results[:, p+1] .^ (1 / 2)
end
